### ISSUE TITLE
[Epic] Cloud publishing

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#208]
Publish easily and automatically without having to install or manage Flowershow yourself with Flowershow Cloud - from obsidian, web, command line etc.

## Acceptance

- [x] Feature analysis done - **✅2022-11-23 https://flowershow.app/notes/design-cloud-publishing**
- [x] MVP implementation

## Tasks

- [x] Analysis of the feature - job stories, v0.1 approach etc #259 

### Original rough outline (2022)

Command to publish markdown to flowershow cloud e.g.

```
cd my-folder-of-markdown-documents
npx flowershow publish
...
...
here is your published site: https://random-xyz.flowershow.app/
``` 

For some more discusssion see https://flowershow.app/meta/publishing-design  especially https://flowershow.app/meta/publishing-design#command-line-or-app--cloud-

**Comment by rufuspollock** [comment]
We have a working system that is open for early access at https://flowershow.app/cloud 🎉

Please register to get access and try it out!
