### ISSUE TITLE
Data presentation in tables and graphs (data literate documents)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#246]
Present data e.g. csv or markdown tables in elegant tables and graphs.

## Tasks

- [x] #286
- [x] Implement **✅2023-12-19 see live example with Flowershow Cloud at https://datarich-demo.flowershow.app**
- [x]  do a write-up (e.g. blog post) about how you use portaljs data presentation components with Flowershow @mohamedsalem401 ** ✅2024-02-02 https://flowershow.app/docs/data-visualization **

**Comment by rufuspollock** [comment]
This is done but not well documented ...

**Comment by saviorand** [comment]
> This is done but not well documented ...

Is there example code somewhere?

**Comment by rufuspollock** [comment]
@saviorand i will check - if not we'll put together a quick example.

**Comment by mohamedsalem401** [comment]
FIXED. https://flowershow.app/docs/data-visualization

**Comment by saviorand** [comment]
@mohamedsalem401 I'm not sure if something changed but the example shows a broken linechart for me? Same when I try to reproduce this [on my website](https://www.valentin.wiki/my-incredible-dataset) following the steps in the guide, but I might be doing something wrong. If I check in the console I see:
`Uncaught SyntaxError: redeclaration of formal parameter eh; note: Previously declared at line 697, column 4004`  
<img width="592" alt="Screenshot 2024-03-10 at 20 06 34" src="https://github.com/datopian/flowershow/assets/37780080/3af92d22-e5fc-496b-8a67-544e13f64bc8">
