### ISSUE TITLE
Create a separate project in our monorepo for our Flowershow website

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#325]
## Acceptance

- [ ] `packages/template` **copied** to `apps/flowershow` (our Flowershow website)
- [ ] `packages/template` adjusted to be a pure Next.js app template
  - [ ] no monorepo related files, e.g. `project.json`
  - [ ] `eslintrc.json`, `tsconfig.json` and other adjusted (not referencing files in parent folders)
  - [ ] `eslint` added back as a dev dependency
  - [ ] starter `content` folder added
  - [ ] started `config.js` file added
  - [ ] ...

**Comment by rufuspollock** [comment]
WONTFIX. we already have an approach where we "install" (ie. symlink) the latest "version" of flowershow to run the website on publishing or for local dev. One day we may want to publish the website more formally but this works for now.

**Comment by olayway** [comment]
@rufuspollock I'd reconsider creating an app for our flowershow website in `flowershow/apps` folder and make the `flowershow/packages/template` a clean template project.

Why: although we have cleaned up the template of unneeded files, there are still some (e.g. Nx's `project.json`, `.eslintrc.json`) that need to stay there if we're treating it as an app as well. They are currently being removed by the CLI but for people who'd like to use the template to jump-start their Next.js project (e.g. using `npx create-next-app --example xxx`), these files will be copied over as well. Another thing is that, in my opinion, the template should also include the `/content` dir with at least a starting `index.md` (now it doesn't have one, since the CLI creates a symlink to external content folder) and a `config.js` file with the set of all the possible config options. It could also have `eslintrc.json` file (but with different content, not referencing parent eslint files in our monorepo as it does now) with some basic settings.

Also: I'd even move the template to examples, as it's neither an app nor an installable package. And I think all other examples we have in there shouldn't be structured like they are now, i.e. external content folder + `.flowershow`, but should also be kind of like different templates, that you can select from when using our CLI, or when running `npx create-next-app --example xxxx`.

@rufuspollock what do you think?

**Comment by rufuspollock** [comment]
Ok, we can think about this. Relative to other things it still seems a bit low priority (but it depends on the cost of doing it).

**Comment by olayway** [comment]
No longer relevant. A separate repository for Flowershow was created here: https://github.com/datopian/flowershow-app
