### ISSUE TITLE
Add .gitignore file to template

### ISSUE THREAD

**Issue by romovpa** [datopian/flowershow#405]
It would be handy to serve the template with an appropriate `.gitignore` for a website. 

A newly installed website has 514Mb big `.flowershow`. At least the node_modules and compiled output probably should not reside in the repository.

[.gitignore from this repository](https://github.com/flowershow/flowershow/blob/main/.gitignore) works well, but might be specific to the project.

**Comment by olayway** [comment]
Done in df602b840dc3898142452921ed1558e2fdb276c8
