### ISSUE TITLE
CI: E2E actions cancelled from time to time

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#438]
## Tasks
- [x] figure out why actions succeed on one Node version and on the other are canceled, even if all tests seem to actually pass (and does the Node version has anything to do with it)

## Notes

E.g. https://github.com/flowershow/flowershow/actions/runs/4203599039/jobs/7293202884

<img width="1582" alt="image" src="https://user-images.githubusercontent.com/52197250/219813776-10fd3b27-b3e4-4726-9b76-2e8074c9a5ec.png">

**Comment by PhilippeduPreez** [comment]
@olayway Is it not due to the time limit?

**Comment by olayway** [comment]
Maybe, but I dunno.. all the tests passed...

**Comment by olayway** [comment]
Or actually no! The CLI E2E tests weren't event run. So it breaks right after the template e2e tests. Maybe it's the teardown script? But why do they pass sometimes? Sometimes it also works if you just manually re-run this job.

**Comment by olayway** [comment]
But you can try increasing the timeouts in playwright and see if it helps.

**Comment by olayway** [comment]
Reopening as it seems timeout has not entirely fixed the issue.

**Comment by olayway** [comment]
@khalilcodes please give it a try with the headless option like you suggested.

**Comment by olayway** [comment]
Closing as no longer relevant. See issue: https://github.com/datopian/flowershow/issues/521
