### ISSUE TITLE
Error when running preview on Windows

### ISSUE THREAD

**Issue by eagle-k** [datopian/flowershow#457]
**Describe the bug**

I am using Windows. The following error occurred during the tutorial https://flowershow.app/docs/publish-tutorial.

```
> npx flowershow@latest preview
⚠ This may not work as expected. You're trying to run Flowershow CLI on Windows, which is not thoroughly tested. Please submit an issue if you encounter any problems: https://github.com/flowershow/flowershow/issues

> @flowershow/template@1.0.0 predev
> npm run generate


> @flowershow/template@1.0.0 generate
> contentlayer build && cross-env NODE_OPTIONS="--experimental-json-modules --experimental-modules" node ./scripts/search.mjs

Warning: Contentlayer might not work as expected on Windows
Error: Found 1 problems in 1 documents.

 └── Encountered unexpected errors while processing of 1 documents. This is possibly a bug in Contentlayer. Please open an issue.

     • "index.md": UnexpectedMDXError: Error: Build failed with 1 error:
     error: Cannot find tsconfig file "undefined/tsconfig.mdx.json"

```

**To Reproduce**

1. Create parent directory

2. Create new vault (Obsidian GUI)
    - Vault name is `my-digital-garden`
    - Location is `some-parent-dir`

3. Create folder `assets` (Obsidian GUI)

4. Set `assets` as attachment folder (Obsidian GUI)

5. Create new `index.md` note (Obsidian GUI)

6. Run `cd some-parent-directory`

7. Run `npx flowershow@latest install`
    - ? Create Flowershow project in current directory? Yes
    - ? Path to the folder with your markdown files my-digital-garden
    - ? Select a folder with your assets (attachments) assets

8. Run `npx flowershow@latest preview`

9. The error described above occurs.

**Versions**
 - OS: Windows 10
 - Node: v18.14.2
 - Npm: 9.5.0
 - PowerShell: 7.3.2

**Comment by rufuspollock** [comment]
INVALID. WONTFIX. we are no longer using contentlayer so this isn't relevant anymore.
