### ISSUE TITLE
Avatarplaceholder does not load

### ISSUE THREAD

**Issue by regalialong** [datopian/flowershow#486]
**Describe the bug**
[packages/template/public/_flowershow/avatarplaceholder.png (permalink)](https://github.com/datopian/flowershow/blob/714d580d22b89b3a640e801c04773c38d249da0e/packages/template/public/_flowershow/avatarplaceholder.png) is stored as an LFS file which is not resolved by npm. Provisioning a new installation therefore provisions the file as LFS reference which a browser can't load.

**To Reproduce**
Set up a new Node installation
Set up a Flowershow installation
Preview or export so that the public folder exists on the file system.

**Expected behavior**
avatarplaceholder.png is stored as actual non-LFS png so that a browser can render it without manually replacing the file.

**Additional context**
I was asked by rufuspollock on Discord to open this.

**Comment by olayway** [comment]
Fixed with 2276420 and 4a5dc8c.

@regalialong Thank you for reporting this!
