### ISSUE TITLE
Giscus comments have broken as we relocated the repository to a different org

### ISSUE THREAD

**Issue by rufuspollock** [datopian/flowershow#490]
See e.g. bottom of https://flowershow.app/docs/comments#developers

![image](https://user-images.githubusercontent.com/180658/234379167-209a1143-56ea-4091-8959-72131b130a19.png)

I think this is probably an easy fix as all the discussions and comments are still there - just in this new location at datopian/flowershow!

**Comment by khalilcodes** [comment]
@rufuspollock we would need to install the giscus app https://github.com/apps/giscus on the datopian/flowershow repo. After this we can update the env variables. Don't have access to 2FA for doing that.

<img width="439" alt="Screen Shot 2023-04-29" src="https://user-images.githubusercontent.com/42637597/235302786-e2fe6527-6280-4ba2-80af-a84983bbeb1f.png">

**Comment by khalilcodes** [comment]
@rufuspollock fixed.

- [x] installed giscus app on `datopian/flowershow`
- [x] updated env variables (repo name)

<img width="512" alt="Screen Shot 2023-04-29" src="https://user-images.githubusercontent.com/42637597/235305653-46cb309b-850b-4bae-8cf7-497396b57492.png">

**Comment by rufuspollock** [comment]
FIXED.
