### ISSUE TITLE
How hot-reload for MD files is implemented in Contentlayer

### ISSUE THREAD

**Issue by olayway** [datopian/flowershow#502]
## Acceptance
- [x] find out how hot-reload for MD files is implemented in contentlayer

### Summary
- when contentlayer is run in development mode:
	- contentlayer config file is read and esbuild [watch mode](https://esbuild.github.io/api/#watch) is used to watch for  any changes to it
	- then, config values read from the file are used to generate the output `.contentlayer/generated` folder, but also, along the way, the content folder starts being watched for any changes using [Chokidar](https://github.com/paulmillr/chokidar)

More info here:
https://github.com/datopian/flowershow/blob/main/site/content/notes/markdown-hot-reload.md

**Comment by olayway** [comment]
@rufuspollock I've added some notes here https://raw.githubusercontent.com/datopian/flowershow/main/site/content/notes/markdown-hot-reload.md
The summary is also in the issue description.

**Comment by rufuspollock** [comment]
@olayway any recommendation on whether we could reuse this in flowershow - note here i think this would be less a "built-in" and more a "howto" to start with.

**Comment by mohamedsalem401** [comment]
FIXED. https://github.com/datopian/flowershow/pull/620
