### ISSUE TITLE
Edit this page does not redirect correctly

### ISSUE THREAD

**Issue by lyqht** [datopian/flowershow#506]
**Describe the bug**

I was looking at the docs at https://flowershow.app/docs, but clicking the "Edit this page" results in 404. I suspect other pages may also have the same problem.

**Expected behavior**
It should not be 404

**Screenshots**
![CleanShot 2023-05-23 at 16 57 57](https://github.com/datopian/flowershow/assets/35736525/a09e90bf-3c04-4c8e-9eca-11fec64bf8df)

**Comment by olayway** [comment]
@lyqht Thanks for reporting! Fixed :)
