### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by lyqht** [datopian/flowershow#507]
fyi the image is broken on README, and I looked around the few flowershow repos, but the `obsidian-vs-flowershow` can't be found anywhere so I'm not sure what to replace it with as well. 

So just letting u guys to know to replace it 😊

<img width="912" alt="CleanShot 2023-05-23 at 17 00 32@2x" src="https://github.com/datopian/flowershow/assets/35736525/22aa8b81-8de9-48c4-83d5-599fd4a004b0">

**Comment by olayway** [comment]
@lyqht Thank you very much for reporting that! Fixed :)
