### ISSUE TITLE
Invalid URL in npx command (npx create-next-app@latest)

### ISSUE THREAD

**Issue by hanmango-o** [datopian/flowershow#528]
Invalid information in using the npx command in https://flowershow.app/blog/2023-02-16-nextjs-tutorial.

```
npx create-next-app@latest --example https://github.com/flowershow/flowershow/tree/main/packages/template
```
In document, The url does not exist in this command.

I think it should be revised as below.
```
npx create-next-app@latest --example https://github.com/datopian/flowershow/tree/main
```

If not, please correct it.

**Comment by rufuspollock** [comment]
@hanmango-o thanks for flagging - would you be up for submitting a PR to correct this?

**Comment by Gutts-n** [comment]
PR for this issue: https://github.com/datopian/flowershow-app/pull/8

CC: @anuveyatsu
