### ISSUE TITLE
Frontmatter Related Issue

### ISSUE THREAD

**Issue by avinashkanaujiya** [datopian/flowershow#539]
Hi guys
Awesome job on this.
I am facing a issue regarding the frontmatter in my notes, I have a habit of adding lots of frontmatter, which gets used in a variety of places.
But they are not rendering in flowershow, properly.
Can anyone, help me regarding this?

**Comment by avinashkanaujiya** [comment]
do frontmatter only work in blog folder?

**Comment by avinashkanaujiya** [comment]
got it, there were non-standard characters in my frontmatter, %file-name% so that metatable can link to files in obsidian

**Comment by avinashkanaujiya** [comment]
is there a possibility for support for this character or linking

**Comment by rufuspollock** [comment]
@avinashkanaujiya we'd have to look at what characters are supported in yaml frontmatter by default.

**Comment by rufuspollock** [comment]
WONTFIX. For now i'm going to close as wontfix as i don't think we plan to support this near-term.
