### ISSUE TITLE
Transclusions/Note embeddings cause hydration errors

### ISSUE THREAD

**Issue by Mr-Pine** [datopian/flowershow#545]
Currently, if a markdown file contains an Obsidian-style transclusion like `![[my-other-note.md]]` you get an error in dev mode <details>
<summary>Error message</summary> 

![image](https://github.com/datopian/flowershow/assets/50425705/d867c21d-bb63-486c-b1bc-3f7eab0f9d5f)

</details>

and nothing happens in export mode.

I understand that that is a pretty big feature, but I have found very litte (up to date) information on whether and when support for transclusions is planned.

In the meantime, it might make sense to transform transclusions into normal links, so that not all functionality is lost and the site is not unusable in dev mode

**Comment by olayway** [comment]
@Mr-Pine thank you for submitting the issue! I totally agree, Obsidian note embeds shouldn't throw an error and at least temporarily should be converted to links. I'll take care of it!

**Comment by olayway** [comment]
@Mr-Pine  This has just been fixed. Thanks again for reporting this issue! 🌷

**Comment by Mr-Pine** [comment]
Awesome!
