### ISSUE TITLE
Flowershow default template is not responsive for larger screens

### ISSUE THREAD

**Issue by Gutts-n** [datopian/flowershow#566]
![image](https://github.com/datopian/flowershow-app/assets/57202549/2c17fbef-84d3-4c31-bf25-0fa9a250ec02)

**Comment by M27afk** [comment]
@rufuspollock I can help on this issue!
Can I get assigned?

**Comment by olayway** [comment]
@M27afk Yay! I'm glad you want to help us! 🙌 I've just assigned you to this issue. Let me know if you need any assistance.

**Comment by M27afk** [comment]
[https://github.com/datopian/portaljs/pull/1029](url)

@olayway  I've created a PR in portaljs repo.
