### ISSUE TITLE
Markdown Table Overflow Issue

### ISSUE THREAD

**Issue by matthew-sessions** [datopian/flowershow#583]
This is the current behavior when you have a table with many columns:
![2023-10-23_16-20-22 (1)](https://github.com/datopian/flowershow/assets/53715422/385ec4b3-7d18-464e-9eaf-4af12c7ecdad)

I patched this on my end here:
https://github.com/datopian/flowershow/blob/5b4cd3a5bfc8d4898c442a9cbb81fccd1e6f77a3/components/MdxPage.tsx#L12
with:
```typescript
const components = {
    mermaid: Mermaid,
    pre: Pre,
    table: (props) => (
        <div className="overflow-x-auto">
            <table {...props} />
        </div>
    ),
};
```
![2023-10-23_16-23-43 (1)](https://github.com/datopian/flowershow/assets/53715422/8d87736a-82c4-41f4-9b8f-2fe613aae634)

**Comment by rufuspollock** [comment]
@matthew-sessions nice fix thank-you. We'll look into getting that in to core.

@davidgasquez do you want to check if you can reproduce that?

**Comment by davidgasquez** [comment]
Was able to reproduce with:

```
| Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      | Tables   |      Are      |  Cool |
|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|----------|:-------------:|------:|
| col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | col 1 is |  left-aligned | $1600 |
| col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned |    $1 |
| col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned | col 3 is | right-aligned |    $1 |
```

![image](https://github.com/datopian/flowershow/assets/1682202/fbcf9702-aedb-4e51-a492-c6af1a8ebfad)

Adding the proposed change fixes it.

![image](https://github.com/datopian/flowershow/assets/1682202/0cddd80a-ce79-4e34-8e27-8d289374c0b6)

That said, [things are still off when you maximice the page in a widescreen](https://github.com/datopian/flowershow/issues/580#). 

![image](https://github.com/datopian/flowershow/assets/1682202/10365fec-3752-42a3-9d73-d70d88e502bb)

**Comment by olayway** [comment]
@davidgasquez, @rufuspollock I've just fixed the layout so now, with @matthew-sessions' fix the tables display correctly even on large screens:

<img width="1582" alt="image" src="https://github.com/datopian/flowershow/assets/52197250/6fb62486-de5b-4443-bb85-041f5439cc44">

I took the liberty of adding Matthew's fix to the template.
Thank you @matthew-sessions 🎉👏
