### ISSUE TITLE
Buggy page in Flowershow website

### ISSUE THREAD

**Issue by blacklightpy** [datopian/flowershow#605]
The page https://flowershow.app/excalidraw/customizability-vs-upgradeability-efficient-frontier-2022-06-26 shows: `Application error: a client-side exception has occurred (see the browser console for more information).`

Console log:
```
SyntaxError: missing ) after formal parameters
    > NextJS (13)
[framework-73b8966a3c579ab0.js:9:69816](https://flowershow.app/_next/static/chunks/framework-73b8966a3c579ab0.js)
SyntaxError: missing ) after formal parameters
    > NextJS (13)
[main-ac5ba36561402fe9.js:1:10151](https://flowershow.app/_next/static/chunks/main-ac5ba36561402fe9.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by rufuspollock** [comment]
@blacklightpy good point - excalidraw stuff should be excluded from the build in fact.

Low priority though as no-one should ever find / go to those pages 😄

**Comment by blacklightpy** [comment]
@rufuspollock I was searching for something and saw a result with `^alnum-sequence` and that's how I got this page. So it would make sense it was not normally meant to be found.

**Comment by olayway** [comment]
I'm disabling the search field for now as it's buggy in general, the search results don't seem to be up to date and so it's not very useful, only annoying.
