### ISSUE TITLE
Larger project gets SQLITE_ERROR: too many terms in compound SELECT when building

### ISSUE THREAD

**Issue by honzasladek** [datopian/flowershow#613]
Hi everyone, I'm getting this error `SQLITE_ERROR: too many terms in compound SELECT` when trying to build the site. Not sure what is the best way to work around that, can you advice? Thanks!

**Comment by honzasladek** [comment]
Ok, found this issue: https://github.com/datopian/markdowndb/issues/22 and upgrade to mddb 0.9 (released two weeks ago) fixes this. I'm closing this but would be probably good to update in main of flowershow.

**Comment by rufuspollock** [comment]
@mohamedsalem401 can you update dependency in flowershow asap to mddb 0.9

**Comment by rufuspollock** [comment]
@honzasladek thanks for highlighting this!

**Comment by mohamedsalem401** [comment]
> @mohamedsalem401 can you update dependency in flowershow asap to mddb 0.9

@rufuspollock This's done https://github.com/datopian/flowershow/commit/35823463f99b6116446d878625d6f02488f6c991
