### ISSUE TITLE
User config has no type

### ISSUE THREAD

**Issue by homostellaris** [datopian/flowershow#625]
This makes it quite difficult to know what's supported when hosting Flowershow yourself.

**Comment by homostellaris** [comment]
I'm raising a PR for this shortly btw just creating the issue 👍

**Comment by mohamedsalem401** [comment]
@homostellaris
Thanks again for those changes, with this PR you're helping a lot of people as this will make it much easier to work with Flowershow configuration. However, it would be better if you could move the changes to the right repo, which is https://github.com/datopian/portaljs/blob/main/packages/core/src/config/default.ts.

Let me know if you will be able to do this, or if I should take it from here. 🤝
