### ISSUE TITLE
All the images in your website are down.

### ISSUE THREAD

**Issue by nightlightouo** [datopian/flowershow#633]
https://flowershow.app/docs/publish-howto
![image](https://github.com/datopian/flowershow/assets/118454986/c39275d2-eb9e-423f-ae62-4dcfb611f1c5)

**Comment by rufuspollock** [comment]
@nightlightouo thanks for reporting. That is odd.

@mohamedsalem401 could you take a look at this.

**Comment by rufuspollock** [comment]
FIXED. This was 🤦‍♂️ error where symlink to assets folder was broken in the build. FIXED and all now working. Thanks for reporting.
